apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "demochart.fullname" . }}-test-connection"
  annotations:
  "helm.sh/hook": "test"
  "helm.sh/hook-weight": "1"
  "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: "test-nginx"
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['wget']
      args: ['{{ include "demochart.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: OnFailure
  