apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-dev-role
rules:
- apiGroup: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-dev-role-binding
subjects:
- users: ["dev-user"]
  kind: User
  apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: cluster-dev-role
    apiGroup: rbac.authorization.k8s.io
