apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: Cron-Job
  labels:
    app: reporting-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - name: reporting container
              image: reporting-tool
          restartPolicy: Never      
