apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-pod
  namespace: kube-system
spec:
  containers:
  - name: custom-scheduler-container
    image: k8s.gcr.io/kube-scheduler-amd64:v1.xx.xx
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --config=/etc/kubernetes/custom-scheduler.yml

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-custom-scheduler
  labels:
    app: app-pod
    type: frontend
spec:
  containers:
  - name: nginx-app
    image: nginx
  schedulerName: custom-scheduler-pod
