apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: my-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: front-end