apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
  initContainers:
  - name: init-service-container
    image: busybox
    command: ["sh", "-c", "sleep", "10"]
