apiVersion: batch/v1
kind: Job
metadata:
  name: job-def
  labels:
    app: job-app
spec:
  backOffLimit: 25
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - name: job-container
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never
