---
# By Default resource requests, limits are not set on Pod Spec.
# Use the below manifest to set some defaults in all the newer containers pods.
apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
    - default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
      type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
    - default:
        cpu: 1m
      defaultRequest:
        cpu: 0.5m
      type: Container
