apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  labels:
    app: app-pod
    type: frontend

spec:
  containers:
  - name: nginx-app
    image: nginx
    env:
    - name: key
      value: value
  restartPolicy: Never/Always(default)/OnFailure
