---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  labels:
    app: app-pod
    type: frontend
spec:
  containers:
    - name: nginx-app
      image: nginx
      env:
        - name: key
          value: value
      resources:
        requests:
          cpu: 50m
          memory: 250Gi
        limits:
          cpu: 200m
          memory: 500Gi
  restartPolicy: Never/Always(default)/OnFailure
