apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: default
rules:
- apiGroup: [""]
  resources: ["pods"]
  resourceNames: ["hello"]
  verbs: ["get", "list", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
subjects:
- users: ["dev-user"]
  kind: User
  apiGroup: rbac.authorization.k8s.io
roleRef:
  - kind: Role
    name: developer-role
    apiGroup: rbac.authorization.k8s.io
