apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: front-end
      image: nginx
      livenessProbe:
        httpGet:
          path: /path/health
          port: http
        initialDelaySeconds: 30
        periodSeconds: 20
        timeoutSeconds: 300
      readinessProbe:
        httpGet:
          path: /path/health
          port: http
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 300