---
apiVersion: v1
kind: Pod
metadata:
  name: resourcelimit
  labels:
    app: resource
spec:
  containers:
    - name: simple web container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 1
          memory: "1Gi"
        limits:
          cpu: 2
          memory: "5Gi"
