---
# to limit cpu, memory usage for all the pods within cluster's namespace.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: abhi
spec:
  hard:
    pods: 10
    requests.cpu: 1
    requests.memory: 5Gi
    limits.cpu: 2
    limits.memory: 15Gi
