apiVersion: v1
kind: Pod
metadata:
  name: dummypod
  labels:
    app: frontend
spec:
  containers:
    - name: nginx
      image: nginx
  serviceAccount: kube-service-account
#automountServiceAccountToken: false
