apiVersion: v1
kind: Service
metadata:
  name: NodePort-service
spec:
  type: NodePort
  ports:
   - targetPort: 8080
     port: 80
     nodePort: 30007
  selector:
    app: app-pod
    type: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: ClusterIP-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: app-pod
    type: backend

