
## VolumeSnapshotClass resource

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: sample-vsnapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: pd.csi.storage.k8s.io
deletionPolicy: Delete
parameters:
  labels: tier=backend

---

## VolumeSnapshot resource

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  volumeSnapshotClassName: sample-vsnapclass
  source:
    persistentVolumeClaimName: pvc-test # already exists in namespace
# status:
#  readyToUse: false/true # once it turns to true; PVC can only be restored and consumed.

---

## Restore PersistentVolumeClaim from a VolumeSnapshot

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
spec:
  storageClassName: csi-pd-standard-sc
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi