apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deplyment
    name: my-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies: 
      - containerName: "my-app"
         minAllowed:
           cpu: "250m"
         maxAllowed:
           cpu: "500m"
         controlledResources: ["cpu"]
        
