prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: job-name
        scrape_interval: 15s
        metrics_path: /myapp/metrics
        static_configs:
        - targets: ['IP:8081']
