# creates secret for service account with non expiry token. [Not recommended]
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecret
  annotations:
    kubernetes.io/service-account-token: service-account-name
