# Mapping custom service account to pod. 
# Existing pod cant be modified to use different service account; 
# It has to be either deleted & created or used in deployment object where service account property can be modified.
apiVersion: v1
kind: Pod
metadata:
  name: dummypod
  labels:
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  serviceAccount: kube-service-account
#automountServiceAccountToken: false
