apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: otel-collector-cluster
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-09-02T05:00:26Z"
  generation: 1
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: otel-collector-cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: opentelemetry-collector
    app.kubernetes.io/version: 0.133.0
    helm.sh/chart: opentelemetry-collector-0.132.0
  name: otel-collector-cluster-opentelemetry-collector
  namespace: default
  resourceVersion: "2560442"
  uid: 8088a949-3e84-4ae9-bc46-237cce42da4e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: otel-collector-cluster
      app.kubernetes.io/name: opentelemetry-collector
      component: standalone-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 84acc7a18d032e604074b45a2b765d6becc9dcb3f953690a243ad55792ea6eb3
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: otel-collector-cluster
        app.kubernetes.io/name: opentelemetry-collector
        component: standalone-collector
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --config=/conf/relay.yaml
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: otel/opentelemetry-collector-k8s:0.133.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: opentelemetry-collector
        ports:
        - containerPort: 6831
          name: jaeger-compact
          protocol: UDP
        - containerPort: 14250
          name: jaeger-grpc
          protocol: TCP
        - containerPort: 14268
          name: jaeger-thrift
          protocol: TCP
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: opentelemetry-collector-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: otel-collector-cluster-opentelemetry-collector
      serviceAccountName: otel-collector-cluster-opentelemetry-collector
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: relay
            path: relay.yaml
          name: otel-collector-cluster-opentelemetry-collector
        name: opentelemetry-collector-configmap
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-02T05:00:31Z"
    lastUpdateTime: "2025-09-02T05:00:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-02T05:00:27Z"
    lastUpdateTime: "2025-09-02T05:00:31Z"
    message: ReplicaSet "otel-collector-cluster-opentelemetry-collector-5f979759d6"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
