apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: pvc-restore-suite
tests:
  - name: restore-pvc-tenant-vsclass-validation
    template: constraint-template.yaml
    constraint: example/constraint.yaml
    cases:
      - name: "Allow - Valid PVC restore attempt by tenant"
        object: tests/valid-pvc.yaml
        inventory:
          - tests/volumesnapshot-inventory.yaml
        assertions:
          - violations: no
      - name: "Deny - Invalid PVC restore - Snapshot doesnt exist"
        object: tests/invalid-pvc-no-snapshot.yaml
        inventory:
          - tests/namespace-inventory.yaml
        assertions:
          - violations: yes
      - name: "Deny - Invalid PVC restore - snapshot status is not ready "
        object: tests/invalid-pvc-not-ready-snapshot.yaml
        inventory:
          - tests/volumesnapshot-inventory.yaml
          - tests/namespace-inventory.yaml
        assertions:
          - violations: yes
      - name: "Deny - Invalid PVC restore - mismatched volumesnapshotclass"
        object: tests/valid-pvc.yaml
        inventory:
          - tests/volumesnapshot-inventory.yaml
          - tests/namespace-inventory.yaml
        assertions:
          - violations: yes
