---
- name: Setup apache
  hosts: webserver
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: Start service
      service:
        name: httpd
        state: started

- name: Setup tomcat
  hosts: appserver
  tasks:
    - name: install tomcat
      yum:
        name: tomcat
        state: installed
    - name: Start service
      service:
        name: tomcat
        state: started