---
name: YAML Lint Workflow

on: [workflow_dispatch, push, pull_request]

jobs:
  yamllint:
    name: YAML Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install YAML Lint
        run: |
          pip install pip --upgrade
          pip install yamllint

      - name: Lint YAML files
        run: |
          # find YAML files recursively
          find . \( -name "*.yaml" -o -name "*.yml" \) -exec ls {} \;

          # Lint YAML files.
          find . \( -name "*.yaml" -o -name "*.yml" \) -exec yamllint {} \; 
